name: Run XUnit Tests

on:
  push:
    branches:
      - master

jobs:
  build-and-test-UI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Replace with the desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --logger trx --filter Package="GUI_Regression"

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: '**/*.trx'

  build-and-test-Api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Replace with the desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --logger trx --filter Package="API_Regression"

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: '**/*.trx'
